# import the libraries

In [1]:
from sklearn.datasets import load_diabetes

In [2]:
import pandas as pd
import numpy as np

In [3]:
ld =  load_diabetes()

In [5]:
ld.feature_names

['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']

In [6]:
ld.target_filename

'C:\\ProgramData\\Anaconda3\\lib\\site-packages\\sklearn\\datasets\\data\\diabetes_target.csv.gz'

In [7]:
ld.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [8]:
# load the dataset

In [9]:
X,y = load_diabetes(return_X_y = True)

In [10]:
X

array([[ 0.03807591,  0.05068012,  0.06169621, ..., -0.00259226,
         0.01990842, -0.01764613],
       [-0.00188202, -0.04464164, -0.05147406, ..., -0.03949338,
        -0.06832974, -0.09220405],
       [ 0.08529891,  0.05068012,  0.04445121, ..., -0.00259226,
         0.00286377, -0.02593034],
       ...,
       [ 0.04170844,  0.05068012, -0.01590626, ..., -0.01107952,
        -0.04687948,  0.01549073],
       [-0.04547248, -0.04464164,  0.03906215, ...,  0.02655962,
         0.04452837, -0.02593034],
       [-0.04547248, -0.04464164, -0.0730303 , ..., -0.03949338,
        -0.00421986,  0.00306441]])

In [11]:
y

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

# train our model 

In [14]:
from sklearn.ensemble import RandomForestRegressor

In [15]:
rf_regressor = RandomForestRegressor(random_state= 101)

In [16]:
rf_regressor.fit(X_train,y_train)

RandomForestRegressor(random_state=101)

# prediction and evaluation part

In [17]:
y_pred = rf_regressor.predict(X_test)

In [18]:
y_pred

array([147.06, 173.64, 139.65, 260.62, 125.45, 126.85, 240.21, 199.13,
       143.95, 176.29, 100.54, 166.14,  83.99, 235.99,  89.46, 136.47,
       220.1 , 280.61, 210.56, 217.62, 137.21, 110.72,  69.56, 200.36,
       129.58, 187.17, 203.72, 155.36,  77.18, 112.93, 217.81, 108.94,
       181.35, 204.68, 135.31, 211.54,  90.09, 110.95, 181.42,  81.64,
        77.59, 106.17, 172.44, 136.62, 168.18,  89.77,  82.15, 122.27,
        79.04, 147.3 , 120.31,  99.13, 171.11, 103.55, 191.88, 135.7 ,
        97.06, 213.86,  95.3 ,  80.8 , 151.51, 163.18, 141.77, 107.55,
       126.24, 227.83, 187.17, 180.01, 153.71, 132.05, 156.66, 221.76,
       204.94, 115.27,  81.17, 167.  , 200.26, 160.43, 183.95, 198.28,
       101.58, 123.37,  84.81,  79.43,  88.57,  72.92,  89.43,  72.68,
       150.73, 205.24, 108.41, 220.32,  82.48,  70.81,  83.77, 184.11,
       251.83, 129.73, 113.48,  83.6 , 215.52,  90.46, 296.19, 129.26,
       183.96, 125.  , 122.33, 125.73, 185.96, 205.51, 115.47, 212.06,
      

In [19]:
from sklearn import metrics

In [25]:
print(f"MAE : { metrics.mean_absolute_error(y_test,y_pred)} ")
print(f"MSE : {metrics.mean_squared_error(y_test,y_pred)}")
print(f"RMSE : {np.sqrt(metrics.mean_squared_error(y_test,y_pred))}")

MAE : 45.07780821917808 
MSE : 3137.3859671232876
RMSE : 56.012373339497834


# Grid Search 

In [ ]:
rf_regressor = RandomForestRegressor(random_state= 101)

In [28]:
grid = {
    'n_estimators' : np.arange(5,100,5),
    'max_features' : np.arange(0.1,1.0,0.05)
}

In [30]:
from sklearn.model_selection import GridSearchCV

In [32]:
grid_search = GridSearchCV(RandomForestRegressor(random_state= 101) ,grid ,cv =2,scoring ="r2" ,n_jobs=-1 )

In [33]:
grid_search.fit(X_train,y_train)

GridSearchCV(cv=2, estimator=RandomForestRegressor(random_state=101), n_jobs=-1,
             param_grid={'max_features': array([0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 , 0.55, 0.6 ,
       0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95]),
                         'n_estimators': array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50, 55, 60, 65, 70, 75, 80, 85,
       90, 95])},
             scoring='r2')

In [34]:
grid_search.best_params_

{'max_features': 0.30000000000000004, 'n_estimators': 30}

In [35]:
grid_search.best_score_

0.41181638287612976

In [54]:
rf_regressor = RandomForestRegressor(max_features= 0.30000000000000004,n_estimators= 30 )
rf_regressor.fit(X_train,y_train)
y_pred = rf_regressor.predict(X_test)
print(f"MAE : { metrics.mean_absolute_error(y_test,y_pred)} ")
print(f"MSE : {metrics.mean_squared_error(y_test,y_pred)}")
print(f"RMSE : {np.sqrt(metrics.mean_squared_error(y_test,y_pred))}")

MAE : 43.179680365296804 
MSE : 2876.774132420091
RMSE : 53.63556779246483


# Random Search

In [55]:
from sklearn.model_selection import RandomizedSearchCV

In [56]:
grid = {
    'n_estimators' : np.arange(5,150,5),
    'max_features' : np.arange(0.1,2.0,0.05)
}

In [57]:
random_search =  RandomizedSearchCV(RandomForestRegressor(),grid,cv =2,scoring ="r2" ,n_jobs=-1,verbose = 1 ,n_iter =50 )

In [58]:
random_search.fit(X_train,y_train)

Fitting 2 folds for each of 50 candidates, totalling 100 fits


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:918: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.40734017        nan 0.27493873        nan
        nan        nan 0.39186636 0.39358531 0.35886304 0.26555882
 0.36948987 0.40149867        nan 0.38739635        nan 0.39322118
        nan 0.37367847        nan        nan        nan        nan
        nan 0.40357973        nan 0.33632143        nan        nan
        nan        nan 0.37080203        nan        nan        nan
        nan 0.40869322 0.37135238        nan        nan 0.38967086
        nan 0.37825237        nan        nan 0.3470337  0.39789361
 0.36787005 0.388787  ]
  warnings.warn(


RandomizedSearchCV(cv=2, estimator=RandomForestRegressor(), n_iter=50,
                   n_jobs=-1,
                   param_distributions={'max_features': array([0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 , 0.55, 0.6 ,
       0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95, 1.  , 1.05, 1.1 , 1.15,
       1.2 , 1.25, 1.3 , 1.35, 1.4 , 1.45, 1.5 , 1.55, 1.6 , 1.65, 1.7 ,
       1.75, 1.8 , 1.85, 1.9 , 1.95]),
                                        'n_estimators': array([  5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,  65,
        70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125, 130,
       135, 140, 145])},
                   scoring='r2', verbose=1)

In [59]:
random_search.best_score_

0.4086932204070382

In [60]:
random_search.best_params_

{'n_estimators': 55, 'max_features': 0.30000000000000004}

In [69]:
rf_regressor = RandomForestRegressor(max_features= 0.30000000000000004,n_estimators= 55,random_state= 101 )
rf_regressor.fit(X_train,y_train)
y_pred = rf_regressor.predict(X_test)
print(f"MAE : { metrics.mean_absolute_error(y_test,y_pred)} ")
print(f"MSE : {metrics.mean_squared_error(y_test,y_pred)}")
print(f"RMSE : {np.sqrt(metrics.mean_squared_error(y_test,y_pred))}")

MAE : 43.68767123287671 
MSE : 2957.1688033510695
RMSE : 54.37985659553608
